title: Bushwick Ayuda Mutua
email: bushwickayudamutua@gmail.com
description: A network of Bushwick neighbors supporting neighbors | Una red de vecines respaldando a vecines en Bushwick.
baseurl: ''
basecolor: '#000000' # for browser settings
url: ''
image: 'BAM.svg'
twitter_username: bushwickayuda
github_username: bushwickayudamutua

plugins:
  - jekyll-admin

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock

jekyll_get_json:
  - data: requests
    json: https://file.baml.ink/data/open-requests.json
